# Generated by Django 5.1.5 on 2025-02-02 14:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_rule_color_alter_task_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='codcolor',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
