# Generated by Django 5.1.6 on 2025-02-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_color_codcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='color',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
